### ISSUE TITLE
Cannot read property 'file' on require()

### ISSUE THREAD

**Issue by pschichtel** [myndzi/wtfnode#1]
Upon requiring the module I'm getting the following uncaught exception:

```
uncaughtException: Cannot read property 'file' of undefined date=Tue Jun 30 2015 10:59:32 GMT+0200 (W. Europe Daylight Time), pid=11200, uid=null, gid=null, cwd=d:\Userfiles\phillip.schichtel\Documents\IdeaProjects\twitter, execPath=C:\Program Files\nodejs\node.exe, version=v0.12.3, argv=[C:\Program Files\nodejs\node.exe, d:\Userfiles\phillip.schichtel\Documents\IdeaProjects\twitter\seed.js], rss=73990144, heapTotal=65846016, heapUsed=28315176, loadavg=[0, 0, 0], uptime=194380.5353237, trace=[column=64, file=d:\Userfiles\phillip.schichtel\Documents\IdeaProjects\twitter\node_modules\wtfnode\index.js, function=EventEmitter.on.EventEmitter.addListener, line=57, method=on.EventEmitter.addListener, native=false, column=18, file=d:\Userfiles\phillip.schichtel\Documents\IdeaProjects\twitter\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js, function=Immediate._onImmediate, line=179, method=_onImmediate, native=false, column=17, file=timers.js, function=processImmediate [as _immediateCallback], line=358, method=null, native=false], stack=[TypeError: Cannot read property 'file' of undefined,     at EventEmitter.on.EventEmitter.addListener (d:\Userfiles\phillip.schichtel\Documents\IdeaProjects\twitter\node_modules\wtfnode\index.js:57:64),     at Immediate._onImmediate (d:\Userfiles\phillip.schichtel\Documents\IdeaProjects\twitter\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:179:18),     at processImmediate [as _immediateCallback] (timers.js:358:17)]
```

Node version: 0.12.3
wtfnode version: 0.2.0

**Comment by myndzi** [comment]
I don't know what you've done to reinterpret error output but it's quite unreadable. Can you paste just a normal stack trace?

**Comment by myndzi** [comment]
Actually, is this a modification of the Error object and how it generates stack traces? That would make sense, because it would mean that wtfnode can no longer parse the stack trace correctly. I can/should add some error handling to prevent crashes, but the module will be significantly less useful if it can't point to call sites.

**Comment by pschichtel** [comment]
This error was logged using winston

**Comment by myndzi** [comment]
OK. I see the error, will push a fix shortly.

**Comment by myndzi** [comment]
Can you try your code now, with master?

`npm install git+https://github.com/myndzi/wtfnode` should do it. If it works I'll publish to NPM.

**Comment by pschichtel** [comment]
I'll check it tomorrow

**Comment by myndzi** [comment]
Did you get a chance to check this? I realize you probably encountered this module while trying to troubleshoot something and you may have moved on since, but your help is valuable to improving the module :) If I don't hear from you in another few days I'll just close the issue.

**Comment by pschichtel** [comment]
Sorry, I missed this. But you are right, I was troubleshooting a problem and have it solved already (actually even before I created this issue).

I'll set myself a reminder for tomorrow :)

**Comment by myndzi** [comment]
Ok, thanks :) I'll remind you again if applicable :P

**Comment by pschichtel** [comment]
The issue is solved

**Comment by myndzi** [comment]
Thanks. I'll publish right away :)
