### ISSUE TITLE
__stack definition conflicts with rconsole

### ISSUE THREAD

**Issue by desowin** [myndzi/wtfnode#17]
Package rconsole also uses __stack object. This makes (unpatched) wtfnode and rconsole incompatible.

**Comment by myndzi** [comment]
Sorry 'bout that. 0.5.3 should correct this?

**Comment by desowin** [comment]
It would be nice if these two packages could work without modifications. So I think, yes, 0.5.3 should correct this.

**Comment by myndzi** [comment]
Me too, but I was hoping you would confirm it :)

**Comment by myndzi** [comment]
Closing as fixed since I never got a response and did the thing
