### ISSUE TITLE
Split CLI from index.js

### ISSUE THREAD

**Issue by RobLoach** [myndzi/wtfnode#18]
When processing through Webpack, can get the following error:

```
ERROR in ../~/wtfnode/index.js
Module parse failed: /wtfnode/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| 
| 'use strict';
```

Would be good to split the CLI from the index.js code.

**Comment by myndzi** [comment]
I'm not sure you're doing something that makes sense. Why are you bundling `wtfnode` at all?

**Comment by RobLoach** [comment]
Running tests on a webpack package. The process may not make sense, and there's likely a better way around it. Thought I'd make this issue while I'm doing some more research into it.

**Comment by myndzi** [comment]
I think this is a leftover from when I split out the proxy runner anyway, so I have no objection to removing it. There's a good chance it won't work well or correctly at all in this environment, however. Recommend cloning the repo, making the change, and using `npm link` to get unblocked; I won't be able to update right away

**Comment by RobLoach** [comment]
Thanks a lot, @myndzi. Really appreciate your time here.

**Comment by myndzi** [comment]
0.5.4 is published, see if it fixes your problem?
