### ISSUE TITLE
Can this module function without DTraceProviderBindings?

### ISSUE THREAD

**Issue by pulkitsinghal** [myndzi/wtfnode#20]
I'm using node `v7.10.0`
I installed `wtfcode` globally
When I try to use `wtfnode` via the command line, I run into:
```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/myProject/worker/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
```

It doesn't stop the code but i am unsure if `wtfcode` can do what's needed without `DTraceProviderBindings` so I want to check if they are required?

**Comment by pulkitsinghal** [comment]
My original question still stands:
> Does wtfcode need `'./build/Release/DTraceProviderBindings'` to function?

But I figured out something else that I'd like to share for posterity:
1. My `node_modules` directory is mounted as a shared volume between my host machine and docker containers. Since my machine has various versions of nodejs installed via `nvm`, I usually do this for the sake of predictability by running all `npm install` commands as `docker run imageName npm install ...` because only one nodejs version is baked into the docker image and I cannot screw things up.
2. Anyway, for now I switched to running commands directly in my local machine and after selecting the appropriate nodejs version via nvm, I reran `npm install dtrace-provider@0.8.5` and the missing `./build/Release/DTraceProviderBindings` was put into place.

**Comment by myndzi** [comment]
`wtfnode` [has no dependencies](https://github.com/myndzi/wtfnode/blob/master/package.json); additionally, the path to the package requiring them appears to be in your own code: `at Object.<anonymous> (/myProject/worker/node_modules/dtrace-provider/dtrace-provider.js:18:23`

`dtrace-provider` is what is requiring these, and seems to be directly included in `/myProject/worker`

**Comment by myndzi** [comment]
(So I suspect that the problem has something to do with your docker volume mount and the node version in the container / how you've wired that stuff up)

I suspect the problem may relate to symlinks to non-mounted paths; enter a docker container in your error case, cd to the dtrace-provider path and do an `ls -al` to look for broken symlinks in the build directory perhaps

**Comment by pulkitsinghal** [comment]
Sorry to bother but thanks for the help!

**Comment by pulkitsinghal** [comment]
Thanks!
