### ISSUE TITLE
wtfnode prevents SIGINT handlers from running

### ISSUE THREAD

**Issue by teknopaul** [myndzi/wtfnode#22]
Hi cool toy,  I'm trying to debug why my application does not close. I have two SIGINT handlers that do the cleanup but these are missing something so node does not exit.

When I run with wftnode my cleanup routines don't run at all, it exits listing correct info but some of that info my handlers will cleanup.

**Comment by myndzi** [comment]
Are you using it with require or with the cli?

**Comment by myndzi** [comment]
(nevermind, I see that either would be affected -- I just pushed a change that should fix this, give it a try?)

**Comment by teknopaul** [comment]
OK, cheers for the rapid response, can I install globally from source?  I ran the program with 

    node index myargs...

and it works, my SIGINT handlers are run now.

Thanks

**Comment by myndzi** [comment]
Globally "from source"?

You can use `npm install -g wtfnode` and then `wtfnode <your script> <args>`

**Comment by teknopaul** [comment]
Won't that installed the version in npm?

On 19 Nov 2017 9:25 pm, "Kris Reeves" <notifications@github.com> wrote:

Globally "from source"?

You can use npm install -g wtfnode and then wtfnode <your script> <args>

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/myndzi/wtfnode/issues/22#issuecomment-345546748>, or mute
the thread

**Comment by myndzi** [comment]
Yes, that will install the `npm` package as a cli-accessible command, which you can run. If you are using it as a module, you should install it locally (without `-g`) and require it into your code before any other requires, then call `wtfnode.dump()` as described in [module usage](https://github.com/myndzi/wtfnode#module-usage)

You probably don't want to be installing it as a local module but executing it as a binary.
