### ISSUE TITLE
await util.promisify(setTimeout)(1000)

### ISSUE THREAD

**Issue by frederik-b** [myndzi/wtfnode#23]
using something like `await util.promisify(setTimeout)(1000) // sleep a second`
throws `TypeError: "callback" argument must be a function`
```
const sleep = util.promisify(setTimeout)
doSomething()
await sleep(1000) // wait a second
doSomethingElse()
```
is a rather common pattern in some of my tests but seems to break wtfnode

wtfnode is great and did it's job (I needed to rewrite some sleeps to setTimeout to make it work)
but I wanted to create awareness for the issue

this is running as a module and uses mocha on typescript but this is the probably rather useless stacktrace:
```
1) MainTest
       "after all" hook:
     TypeError: "callback" argument must be a function
      at setTimeout (timers.js:421:11)
      at global.(anonymous function) (/usr/local/opt/backend/node_modules/wtfnode/index.js:134:37)
      at internal/util.js:227:26
      at Function.after (/usr/local/opt/backend/src/Main.test.ts:22:32)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by myndzi** [comment]
Hi, thanks for your report :)

At first glance, it doesn't seem to be a problem with `wtfnode` itself. Looking at line 134, we see this: https://github.com/myndzi/wtfnode/blob/master/index.js#L134

...which is just a wrapper which passes the arguments it was given along to the function it wraps. If you remove `wtfnode` from your test, does it fail with the same error?

It's certainly possible that I goofed something up, but nothing immediately jumps out. If the above does *not* produce the same error, can you try and create a minimal reproduction case for me to troubleshoot with?

Thanks!

**Comment by myndzi** [comment]
Oh, also: are you transpiling this? There seems a strong likelihood of negative interactions with `wtfnode` and something like Babel, so if you are using babel-runtime, ensure that `wtfnode` is loaded before babel-runtime is, and/or include your babel setup in the repro case

**Comment by myndzi** [comment]
(Semi-related: timeouts/sleep in tests can be flaky in general, and certainly slow your tests down -- you might also consider either restructuring to allow you to inject times, or using something like `sinon` to deterministically perform time-dependent tests. Alternately, if you're using promises, you may need to chain them correctly to ensure things happen in the order they're supposed to)

**Comment by myndzi** [comment]
Update: I see what's wrong.

The argument ordering for setTimeout is backwards from the typical callback style. To deal with this, node core uses a symbol property on a function to specify a custom promisification function. This exists for setTimeout to swap the argument order. 

I think I need to copy properties of the function over so that the custom promisification function is copied, too.

**Comment by myndzi** [comment]
0.5.7 published -- see if this addresses your issue?
