### ISSUE TITLE
Exception thrown due to stack file being undefined

### ISSUE THREAD

**Issue by SeanSobey** [myndzi/wtfnode#24]
I am getting an exception in `findCallsite(stack)` in some scenarios. This is happening since `stack[i].file` is undefined.

Maybe a solution would be to filter out the undefined files as well:
```js
    function findCallsite(stack) {
        for (var i = 0; i < stack.length; i++) {
            // Ignore frames from:
            //  - wtfnode by excluding __filename
            //  - builtins by excluding files with no path separator
            //  - internal builtins by excluding files beginning with 'internal/'
            //    (even on windows, the stack trace uses unix separators for these)
            if (stack[i].file &&
                stack[i].file !== __filename &&
                stack[i].file.indexOf(path.sep) !== -1 &&
                stack[i].file.slice(0, 9) !== 'internal/'
            ) {
              return stack[i];
            }
        }
        return null;
    }

Using node v9.5
```

**Comment by myndzi** [comment]
Huh, that's interesting. Under what circumstances is there no filename?

**Comment by myndzi** [comment]
Can you try installing from the git repo/branch: https://github.com/myndzi/wtfnode/tree/missing-file-in-stack and see if it fixes your problem?

I'd like to know why the stack trace behaves this way before publishing, though

**Comment by SeanSobey** [comment]
Yes I also thought it was weird. It is quite a large project but I spent some time investigating and I think I have a bit more context that may be useful:

It is breaking specifically on a gulp task that is running [madge](https://github.com/pahen/madge), `wtfnode` is `required` at the top of the gulp file so I think the hooks are binding fine.

Madge seems to be doing a bunch of things with `vm` that might be related to the issue, but after isolating the exact setup I modified your `getStack()` like so: 
```js
function getStack() {
        var _Error_prepareStackTrace = Error.prepareStackTrace; // <- *A note on this at the end
        var hooked = function (_, stack) { return stack; };
        Error.prepareStackTrace = hooked;
        var err = new Error();
        var stack = err.stack.map(function (item) {
            return {
                file: item.getFileName(),
                line: item.getLineNumber(),
                scriptNameOrSourceURL: item.getScriptNameOrSourceURL(),
                string: item.toString()
            };
        });
        Error.prepareStackTrace = _Error_prepareStackTrace;
        return stack;
    }
```
I then printed out `stack[i]` in `findCallsite()`:
```js
 function findCallsite(stack) {
        for (var i = 0; i < stack.length; i++) {
            if (!stack[i].file) {
                console.log('stack[i]', stack[i]);
            }
            if (stack[i].file !== __filename &&
                stack[i].file.indexOf(path.sep) !== -1 &&
                stack[i].file.slice(0, 9) !== 'internal/'
            ) {
              return stack[i];
            }
        }
        return null;
    }
```
And looks like in this case it is something to do with `eval()` code:
```json
{
    "file": undefined,
    "line": 10,
    "scriptNameOrSourceURL": undefined,
    "string": "eval (eval at thenify.withCallback (<my app dir>\\node_modules\\thenify\\index.js:33:10), <anonymous>:10:8)"
  }
```
I also found that `file` can be `null` as well!
```json
  {
    "file": null,
    "line": null,
    "scriptNameOrSourceURL": null,
    "string": "new Promise (<anonymous>)"
  }
```
Here is a normal callsite for comparison:
```json
  {
    "file": "child_process.js",
    "line": 139,
    "scriptNameOrSourceURL": "child_process.js",
    "string": "exports.exec (child_process.js:139:18)"
  }
```

* Maybe it would be better to late-bind the hook for `Error.prepareStackTrace` to cater for other modules like [source-map-suppport](https://github.com/evanw/node-source-map-support)?

**Comment by myndzi** [comment]
Ah, interesting! Thanks for digging so deeply :)

I agree that taking a reference to `prepareStackTrace` inside `getStack` makes more sense. I don't quite follow what it actually changed/affected, but you've given me enough to reproduce and poke at it, I think.

Does the branch I pushed address your original problem? Presumably the source-map-support thing means that `wtfnode` fails to give the correct pre-translated line references and can be improved, but it might be worth tackling in a separate effort; if the current code works, I can just publish as-is until I've had a chance to set up some working examples of more complicated stuff to make sure I'm doing stuff correctly.

**Comment by SeanSobey** [comment]
Yes the `missing-file-in-stack` branch resolves the original issue and I think will work fine going forward for the `undefined` `eval()` cases as well as what looks like async related `null` files as well.

I agree that the `prepareStackTrace` issue can be separate. I do not know too much about that API itself but I have done fairly similar work around that area with resolving typescript source maps in error stack traces. The [V8 docs](https://github.com/v8/v8/wiki/Stack-Trace-API#customizing-stack-traces) might be helpful with the details.

**Comment by myndzi** [comment]
I have a test case for undefined, but not for null - this should be enough to publish, but for completeness's sake, how did you get null values?

**Comment by myndzi** [comment]
hmm... I wonder if I should bother wrapping the Function constructor and eval to get the line where they were created. I'm not sure wrapping a constructor won't introduce other problems, but I think I can do it. Maybe I can make it optional...

**Comment by myndzi** [comment]
Published 0.6.0 with the fixes mentioned here and a couple extra touches: 
- it will display the origin of where an eval function was defined if it fits the normal rules, e.g. is in your application code
- fix function name on udp message handlers(?)
- added a couple "test" files for the cases raised here

(It should be noted that most of these tests aren't proper tests, but just things I manually run to make sure everything looks right, heh. Originally I had considered this package to be a big hack for which integration tests wouldn't be terribly useful, but... maybe I should reconsider)

**Comment by SeanSobey** [comment]
Thanks for the updates, I managed to replicate the null scenario, seems like a top-level promise will do it:

test.js:
```js
function getStack() {
	const _Error_prepareStackTrace = Error.prepareStackTrace;
	const hooked = function (_, stack) { return stack; };
	Error.prepareStackTrace = hooked
	const err = new Error();
	const stack = err.stack.map(function (item) {
		return {
			file: item.getFileName(),
			line: item.getLineNumber()
		};
	});
	Error.prepareStackTrace = _Error_prepareStackTrace;
	return stack;
}

new Promise(function (resolve, reject) {
	console.log('test', getStack())
	resolve();
})
```
You will see one of the CallSites is null. I am not sure if there are other ways to get this.

**Comment by myndzi** [comment]
Thanks for running that down! It does indeed seem to be fine (even perhaps on the previous version), but I've added a file to hopefully catch if it starts breaking anything.

TBH I never expected this repo to get as much use as it does -- reports like this make it a pleasure to keep up-to-date with the latest Node versions and hopefully keep helping people find difficult-to-investigate problems! :)
