### ISSUE TITLE
wtfnode does not wait for async-exit-hook to finish running

### ISSUE THREAD

**Issue by james-rabbit** [myndzi/wtfnode#27]
I am using wtfnode to debug some open handles left over when my server stops, and it's working great.

To clean up my open handles on SIGINT, I am using [`async-exit-hook`](https://www.npmjs.com/package/async-exit-hook) and I think I have them all fixed.
If I ctrl-C the server running with node it shuts down fine, but with wtfnode it still reports open handles.

**Comment by myndzi** [comment]
My guess is that the remaining handle(s) are due to async-exit-hook? Can you share the output? Does it still do the same if async-exit-hook is not used?

**Comment by james-rabbit** [comment]
I made a very simple test program to show the difference here:
```javascript
const exitHook = require('async-exit-hook');
exitHook((callback) => {
    console.log('Exit hook called.');
    setTimeout(() => {
        console.log('logging 5 seconds later');
        callback();
    }, 5000);
});
```

Here are the results with node and wtfnode:

With node it ends itself without ctrl-C and prints everything:
```
$ node ./AsyncExitTest.js
Exit hook called.
logging 5 seconds later
```

With wtfnode it requires ctrl-C to stop it, and only logs the synchronous part of the exit hook:
```
$ wtfnode ./AsyncExitTest.js
^CExit hook called.
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Timers:
  - (5000 ~ 5 s) (anonymous) @ /Users/james/code/async-exit-test/AsyncExitTest.js:4
  - (10000 ~ 10 s) (anonymous) @ /Users/james/code/async-exit-test/node_modules/async-exit-hook/index.js:75
- Others:
  - Pipe
```


I was reading the docs for `async-exit-hook` and it does not work with `process.exit()`, so if wtfnode is sending a direct `process.exit()` that might be relevant. Other than that I didn't really find anything that might cause issues here.

**Comment by james-rabbit** [comment]
Ok, it makes sense that the exit handlers conflict.
I fixed my server so that it's shutting down cleanly, so really wtfnode has done its job already.  If I have a problem again, I can debug the issue using manual instrumentation. Thanks!

**Comment by myndzi** [comment]
You're welcome :) Glad it helped you!
