### ISSUE TITLE
Show more information on cluster worker ipc "Pipe"

### ISSUE THREAD

**Issue by NiklasGollenstede** [myndzi/wtfnode#29]
First off, this module is *very* helpful, thanks!

One of the last issues I just had to track down was that I wasn't aware that one needs to call `cluster.worker.disconnect()` for cluster workers to exit cleanly (I thought just closing all servers should be enough). Anyway, `wtfnode` just reported this:
```
[WTF Node?] open handles:
- Others:
  - Pipe
```
Since I didn't have that "Pipe" in my local development, it took me a while to figure out that is is the IPC channel from the cluster worker to the PM2 master.
I think for `wtfnode` it should be fairly straight forward to figure out that this is a IPC channel to another node process (I'm pretty sure this is created in the `setupChannel` function in `internal/child_process.js`) and maybe even that is is the one connecting the current worker to the master.

I know of this problem now, but I imagine a fair amount of developers using this module don't, and then it would be really nice to get more than the `Others - Pipe`.

**Comment by myndzi** [comment]
This might have changed over time, I'm pretty sure I've dealt with cluster before. Thanks for the tip and the reference to where I might be able to hook it. As they keep moving more things into "internal", I'm having a harder and harder time obtaining a reference somewhere that I can get useful information! I will have a look as soon as I'm able.

Is it possible you can provide a minimal working example? I see you mention PM2, but when using PM2 in cluster mode I believe it controls the loading of the module. In such a case, it may be out of my control -- I depend very much on having wtfnode loaded before anything else, so that references other modules get from requiring things are the ones I've hooked, rather than the version before I've done so. It will help me find a solution if I can reproduce exactly what you are encountering.

(Also, which node version?)

**Comment by NiklasGollenstede** [comment]
> As they keep moving more things into "internal", I'm having a harder and harder time obtaining a reference somewhere that I can get useful information!

Yeah. in terms of software design it is good that they do, but it makes hacks like this difficult. I had similar problems with another project.

> Is it possible you can provide a minimal working example?

I created a Gist: https://gist.github.com/NiklasGollenstede/1c17f213659615b5e9c1f66923f3b740
The result is the same in node v8.9.3 and v10.8.0. It has little to do with PM2, as the Pipe in question is created in the forked process before handing of control to either application code or PM2 (which indeed does some stuff in the forked process).
But as the first tests in the Gist shows, its still very easy to identify the cluster IPC Pipe, its `process.channel`.

And if you do the `instanceof process.binding('pipe_wrap').Pipe` test, you could list the Pipes as "IPC channel to another node process" or something more informative like that (I don't think that class is used for anything else).

> Also, which node version?

My bad. Tested it in versions v8.9.3, v10.8.0, v10.9.0 and 10.10.0 by now.

**Comment by myndzi** [comment]
I see... in my (admittedly brief) cluster test, I assumed that the worker exits at some point/eventually. In your example, the worker doesn't exit -- which causes the parent process to hang, of course.

I'm starting to really feel the desire to rearchitect this more robustly, even though it's a giant hack. This one is an easy fix though :) Even works back to 0.10 with a minor change.

See if `wtfnode@beta` does what you expect. Also see https://github.com/myndzi/wtfnode/tree/parent-ipc#ipc-channel-to-parent for new docs.

Output should look like:

```
- Others:
  - IPC channel to parent (see readme)
```

**Comment by NiklasGollenstede** [comment]
Looks good!
I think you could additionally mark everything else that is `instanceof process.binding('pipe_wrap').Pipe` "IPC channel to a child process" or "IPC channel to another process", to get a better output in the parent as well.

But that is not what this ticket was originally about, so I'll close this now. Thanks!

**Comment by myndzi** [comment]
Child processes have more information already, since I can instrument what spawned them :) the full output from the cluster test looks something like this:
```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Cluster workers
  - PID 20493
    - Entry point: /home/myndzi/wtfnode/tests/test-cluster.js:7
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Others:
  - IPC channel to parent (see readme)
```

**Comment by myndzi** [comment]
(merged and published to latest)

**Comment by NiklasGollenstede** [comment]
Uhh. Fancy
