### ISSUE TITLE
Error: No such module: timer_wrap

### ISSUE THREAD

**Issue by FallingSnow** [myndzi/wtfnode#32]
```
$ node --version
v11.1.0
```
Using wtfnode in my server results in:
```js
<fatal> /home/[redacted]/node_modules/wtfnode/index.js:1
Error: No such module: timer_wrap
    at binding (internal/bootstrap/loaders.js:81:36)
    at process.binding (internal/bootstrap/node.js:428:9)
    at /home/[redacted]/node_modules/wtfnode/index.js:297:21
    at Object.<anonymous> (/home/[redacted]/node_modules/wtfnode/index.js:338:3)
    at Object.<anonymous> (/home/[redacted]/node_modules/wtfnode/index.js:1)
```

**Comment by FallingSnow** [comment]
Might be related to: https://github.com/nodejs/node/commit/2930bd1317

**Comment by myndzi** [comment]
Probably. I'll see what I can do. If I don't need timer_wrap in 11.1 it should be an easy fix, but seems like I should put some time into 1.0, which has dynamic loading functionality for different versions ;)

**Comment by myndzi** [comment]
Sorry for the delay on this. I just got looking into it, and it seems that timers no longer show up in `process._getActiveHandles()`, which stinks. I'm trying to find a way to get a list of timers that may be keeping the process alive, but I may have to maintain my own list, and then... I dunno? Check if they are ref'd? :(

**Comment by myndzi** [comment]
Looks like this may be the future way to go: https://nodejs.org/api/async_hooks.html

**Comment by myndzi** [comment]
@FallingSnow can you try out `wtfnode@beta` and verify that it solves your problem?

**Comment by krzysztof-jelski** [comment]
@myndzi I had the same problem, tried `wtfnode@beta`, works perfectly! Thanks!

**Comment by myndzi** [comment]
Great! :) Thanks for the report, sorry it took so long!

**Comment by RobLoach** [comment]
Mind releasing this for Node 11 so that we don't have to `@beta` it? :wink:

**Comment by RobLoach** [comment]
WOOO!! Thank you! I'll check it out.

**Comment by markddrake** [comment]
I must be missing something ...

~~~
C:\Development\YADAMU\pump>npm uninstall wtfnode
npm WARN saveError ENOENT: no such file or directory, open 'C:\Development\YADAMU\pump\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Development\YADAMU\pump\package.json'
npm WARN pump No description
npm WARN pump No repository field.
npm WARN pump No README data
npm WARN pump No license field.

removed 1 package in 0.317s
found 0 vulnerabilities


C:\Development\YADAMU\pump>npm install wtfnode
npm WARN saveError ENOENT: no such file or directory, open 'C:\Development\YADAMU\pump\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Development\YADAMU\pump\package.json'
npm WARN pump No description
npm WARN pump No repository field.
npm WARN pump No README data
npm WARN pump No license field.

+ wtfnode@0.8.0
added 1 package from 1 contributor and audited 1 package in 0.437s
found 0 vulnerabilities


C:\Development\YADAMU\pump>wtfnode node\cloneSchema CONFIG=oracle\cloneSchemas.json MODE=DDL_ONLY
internal/bootstrap/loaders.js:129
      mod = bindingObj[module] = getBinding(module);
                                 ^

Error: No such module: timer_wrap
    at process.binding (internal/bootstrap/loaders.js:129:34)
    at C:\Users\Mark D Drake\AppData\Roaming\npm\node_modules\wtfnode\index.js:297:21
    at Object.<anonymous> (C:\Users\Mark D Drake\AppData\Roaming\npm\node_modules\wtfnode\index.js:338:3)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)

C:\Development\YADAMU\pump>node -v
v11.9.0

C:\Development\YADAMU\pump>
~~~ 

Any help much appreciated

**Comment by myndzi** [comment]
I _think_ perhaps you've installed wtfnode globally and it's an old version -- try `npm install wtfnode -g`

Or, create a `package.json` and add something like this:

```
"scripts": {
  "wtfnode": "wtfnode"
}
```

And use `npm run wtfnode etc...`

**Comment by myndzi** [comment]
Basically, when you use `wtfnode` _the command_, it's using the globally-installed package. When you use `require('wtfnode')`, it's using the locally-installed package. So, you're not running the one you just installed / the one you think you're running. Adding to `package.json` will run it from that package's `node_modules` by virtue of including its bin directory in the path
