### ISSUE TITLE
SIGINT is not necessarily the sole signal to monitor

### ISSUE THREAD

**Issue by gautaz** [myndzi/wtfnode#33]
Hello,

SIGINT is not the only signal used to cleanly stop a process, SIGTERM is also commonly used.

A common use case is in a Docker environment where [the default signal used to stop the primary process of a container is SIGTERM](https://docs.docker.com/engine/reference/commandline/stop/). In this particular use case, one wants to know if the NodeJS process drops cleanly all its handles when receiving SIGTERM.

More broadly, people would perhaps want to know how is the NodeJS process behaving when receiving any particular signal.

Would it be possible to pass the signal to monitor as an argument to `wtfnode`?

**Comment by myndzi** [comment]
Hi! Yeah, that shouldn't be too troublesome to do. I expect we'd want two arguments - one to tell it not to wait for a second signal to confirm?

Note: You can use `wtfnode` as a module, too, and implement whatever behavior you want; running it from the CLI isn't the only way. If you're blocked until I get to it, you can just do something like:

```js
const wtf = require('wtfnode');

process.on('whateveryouwant', () => {
  wtf.dump();
  process.exit();
});
```

**Comment by gautaz** [comment]
Hi @myndzi !

This code sample is exactly what I need if it is not available right now with the command line 👍.

Thanks a lot!

**Comment by myndzi** [comment]
Configurability was a bit problematic, so I just added a `SIGTERM` handler. There doesn't seem to be a great deal of value in handling arbitrary signals since there are so many caveats anyway.

**Comment by gautaz** [comment]
@myndzi That's fine as it fills the gap !

You're right, SIGINT and SIGTERM are most of the time the only signals used to stop cleanly a process. It would have been odd for instance to handle signals like SIGCONT.

Thank you again !
