### ISSUE TITLE
CoffeeScript a direct dependency? 😬

### ISSUE THREAD

**Issue by TehShrike** [myndzi/wtfnode#44]
Installing `coffeescript` takes forever/doesn't successfully complete on my machine – it looks like it's only used for a test, so it should probably be a dev dependency?

**Comment by myndzi** [comment]
Oh no, how did that happen 😬 it's definitely only a dev dependency (for testing)

**Comment by myndzi** [comment]
Published 0.9.1 -- let me know if that works for you?

**Comment by TehShrike** [comment]
Sweet, thanks!
