### ISSUE TITLE
FEATURE REQUEST: dumpInInterval() convenience method

### ISSUE THREAD

**Issue by capaj** [myndzi/wtfnode#49]
would be really cool to be able to do this:

```
wtfnode.dumpInInterval(90000)
```

which would be the same as doing

```ts
const handler = setInterval(() => {
  wtfnode.dump()
}, 90000)

handler.unref()
```

**Comment by myndzi** [comment]
Hi there. I'm a bit disinclined to do this, mainly because the point of the tool is to identify dangling handles preventing node from _exiting_. You only exit once, so I'm not sure what purpose this would serve? That and, as you've shown, it can be accomplished with a one-liner. Can you say more about what purpose or benefit it would provide to users?

**Comment by capaj** [comment]
why to include it?
Yes it's 4 liner, but a lot of developers don't know about unref() so a lot of people won't even think of using it this way.

my usecase is running this in jest/vitest or any other test runner and detecting culprit when the runner is not exiting

**Comment by myndzi** [comment]
A timer doesn't really address your use case well - what you probably want is an "afterEach" with a debounce or something (to avoid spam).

That said, `wtfnode` doesn't operate properly if it's not loaded absolutely first; it won't be able to mutate the globals that it wraps to identify callers. So for use with Jest, you'd probably be best off using the cli invocation (to ensure it loads first) to load wtfnode and then launch jest directly and then manually hit ctrl+c as usual when the tests have reported completion. It's not possible of course to know when a program has _intended_ to exit automagically, and certainly waiting for a period of time is not a very convenient way to substitute for that.

I agree that `unref` may be relatively unknown, but I don't agree that it's a particular problem - it will be pretty obvious that "the timer that ran wtfnode" is in the list to a user who is unaware of things. In other words, it doesn't really hurt anything if the timer shows up in the list.

I'm hesitant to commit to an additional API here and I don't honestly see enough value to justify the addition.
