### ISSUE TITLE
Is clearInterval broken by wrapping?

### ISSUE THREAD

**Issue by myndzi** [myndzi/wtfnode#8]
A similar problem to that in https://github.com/myndzi/wtfnode/pull/7 may exist with clearInterval, which also uses an internal Node wrapper

**Comment by efokschaner** [comment]
I suspect not, because it uses a better event registration / de-registration pattern of returning a handle to identify the subscription. Worth testing though.

**Comment by myndzi** [comment]
Seems to be okay, added tests for clearing setTimeout, setInterval, and setImmediate, not bothering to publish a new package though.
